version: '3.3'


services:

  mongo:
    image: ${MONGO_IMAGE}:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - mongodb
          - comment_db
  ui:
    image: ${DOCKERHUB_USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_EXPOSE_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${DOCKERHUB_USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${DOCKERHUB_USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${DOCKERHUB_USERNAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - 9090:${PROMETHEUS_EXPOSE_PORT}/tcp
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - back_net
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb-exporter:
    image: ${DOCKERHUB_USERNAME}/mongodb-exporter:latest
    environment:
      MONGODB_URL: mongodb
    networks:
      - back_net

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - back_net
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    ports:
      - 3000:${GRAFANA_PORT}
    networks:
      - back_net

  alertmanager:
    image: ${DOCKERHUB_USERNAME}/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:${ALERTMANAGER_PORT}
    networks:
      - back_net

  stackdriver_exporter:
    build: stackdriver_exporter
    ports:
      - 9255:${STACKDRIVER_EXPORTER_PORT}
    networks:
      - back_net
    environment:
      - STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID=${STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID}
      - STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES=${STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES}
      - GOOGLE_APPLICATION_CREDENTIALS=/stackdriver.json

      
volumes:
  post_db:
  grafana_data:
networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24

