---
comment:
  service:
    internalPort: 9292
    externalPort: 9292

  image:
    repository: vbrednikov/comment
    tag: latest

  databaseHost:

post:
  service:
    internalPort: 5000
    externalPort: 5000

  image:
    repository: vbrednikov/post
    tag: latest

  databaseHost:

ui:
  service:
    internalPort: 9292
    externalPort: 9292

  image:
    repository: vbrednikov/ui
    tag: latest

  postHost:
  postPort:
  commentHost:
  commentPort:

  ingress:
    class: nginx
