---

# See https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer
#   for details on using reserved external ip
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
 #   kubernetes.io/ingress.global-static-ip-name: ui-ingress-lb
spec:
  tls:
    - secretName: ui-ingress
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "ui.fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
