FROM alpine:latest
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD . $APP_HOME/
RUN apk update && apk upgrade && apk add ruby ruby-dev g++ make && gem install json bundler --no-ri --no-rdoc && bundle install && apk del ruby-dev g++ make
ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292
CMD ["puma"]
